id: I688CCC58
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T02:59:19+00:00'
last_modified: '2022-06-08T05:29:47.790095+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17496
  title: 'གདམས་ངག་མཛོད་ཀྱི་ཙཀླི། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A445:
      image_group_id: I4PD1349
      title: ''
      total_pages: 253
      order: 1
      base_file: A445.txt
    '8068':
      image_group_id: I4PD1350
      title: ''
      total_pages: 71
      order: 2
      base_file: 8068.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
